name: figtrade
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.2
  flutter_native_splash: ^2.2.16
  font_awesome_flutter: ^10.2.1
  rxdart: ^0.27.5
  hive: ^2.2.3
  http: ^0.13.5
  charts_flutter: ^0.12.0
  socket_io_client: ^2.0.0-beta.3
  webview_flutter: ^3.0.4
  awesome_dialog: ^3.0.2
  flutter_timer_countdown: ^1.0.5
  circular_countdown_timer: ^0.2.3
  timer_stop_watch: ^1.0.0
  syncfusion_flutter_charts: ^20.4.50
  fl_chart: ^0.61.0
  k_chart:
    git:
      url: https://github.com/mafanwei/k_chart
  web_socket_channel: ^2.3.0
  stop_watch_timer: ^2.0.0
  flutter_countdown_timer: ^4.1.0
  custom_timer: ^0.2.3
  flutter_cashfree_pg_sdk: ^2.0.9+12
  cashfree_pg: 2.0.10+30
  path_provider: ^2.0.14
  k_chart_pw: ^0.5.6
  quantupi: ^0.0.6
  internet_connection_checker: ^1.0.0+1
  google_sign_in: ^6.1.0
  flutter_launcher_icons: ^0.11.0
  url_launcher: ^6.1.11
  firebase_messaging: ^14.6.0
  flutter_local_notifications: ^14.0.0+2
  firebase_core: ^2.12.0
  share_plus: ^6.3.4
  facebook_app_events: ^0.19.0
  rive: ^0.9.1
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/appicon.png"
  adaptive_icon_background: "#511867"
  adaptive_icon_foreground: "images/ic_launcher.png"
flutter_native_splash:
  color: "#18098f"
  image: "images/appicon.png"
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
