name: earnmoney
description: A new way to Earn.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 3.0.0+3
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.5
  flutter_fortune_wheel: ^1.2.0
  razorpay_flutter: ^1.3.4
  unity_ads_plugin: ^0.3.7
  awesome_notifications: ^0.7.4+1
  getwidget: ^3.0.1
  font_awesome_flutter: ^10.2.1
  http: ^0.13.5
  path_provider: ^2.0.11
  hive: ^2.2.3
  url_launcher: ^6.0.3
  clipboard: ^0.1.3
  flash: ^3.0.1
  gender_picker: ^1.1.0
  share_plus: ^6.3.4
  double_back_to_close: ^2.0.0
  google_sign_in: ^6.1.0
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_core_platform_interface: ^4.5.2
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.1.4
  cloud_firestore: ^4.2.0
  another_flushbar: ^1.12.29
  webview_flutter: ^3.0.4
  webview_cookie_manager: ^2.0.6
  google_mobile_ads: ^2.3.0
  month_year_picker: ^0.2.0+3
  workmanager: ^0.5.1
  rxdart: ^0.27.5
  audioplayers: ^4.0.1
  flutter_native_splash: ^2.2.19
  speech_to_text: ^6.1.1
  just_audio_background: ^0.0.1-beta.9
  flutter_tts: ^3.6.3
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0
  flutter_svg: ^2.0.5
  awesome_dialog: ^3.0.2
  flutter_openmoney: ^0.0.2
  just_audio: ^0.9.32
  confetti: ^0.7.0
  quantupi: ^0.0.5
  connectivity_plus: ^4.0.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  awesome_snackbar_content: ^0.1.3






flutter_native_splash:
  android: true
  ios: true
  web: false
  background_image : 'assets/open.png'

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/Graphics/
    - assets/Sounds/
  
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
