name: cashapp
description: An Earning app.

# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 5.0.0+5

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^4.1.0
  awesome_dialog: ^2.2.1
  awesome_notifications: ^0.7.4+1
  awesome_snackbar_content: ^0.1.3
  change_app_package_name: ^1.1.0
  clipboard: ^0.1.3
  cloud_firestore: ^4.7.1
  confetti: ^0.7.0
  connectivity_plus: ^4.0.1
  contacts_service: ^0.6.3
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  flutter_fortune_wheel: ^1.2.1
  flutter_local_notifications: ^14.1.0
  flutter_tts: ^3.7.0
  font_awesome_flutter: ^10.4.0
  getwidget: ^3.1.1
  google_nav_bar: ^5.0.6
  google_sign_in: ^5.4.4
  hive: ^2.2.3
  http: ^0.13.6
  line_icons: ^2.0.1
  month_year_picker: ^0.2.0+4
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  rxdart: ^0.27.7
  share_plus: ^7.0.2
  unity_ads_plugin: ^0.3.8
  url_launcher: ^6.1.11
  webview_flutter: ^3.0.4
  cupertino_icons: ^1.0.2
  fast_contacts: ^3.0.3
  quantupi: ^0.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Graphics/
    - assets/Sounds/