name: cashapp
description: a way to earn money.
publish_to: 'none'
version: 18.0.0+18

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  # rive: ^0.9.1
  audioplayers: ^4.1.0
  quickalert: ^1.0.1
  awesome_notifications: ^0.7.4+1
  awesome_snackbar_content: ^0.1.1
  clipboard: ^0.1.3
  cloud_firestore: ^4.8.0
  confetti: ^0.7.0
  connectivity_plus: ^4.0.1
  contacts_service: ^0.6.3
  cupertino_icons: ^1.0.5
  fast_contacts: ^3.0.3
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.2.1
  flutter_local_notifications: ^14.1.1
  flutter_tts: ^3.7.0
  font_awesome_flutter: ^10.4.0
  getwidget: ^3.1.1
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.1.3
  hive: ^2.2.3
  http: ^0.13.6
  line_icons: ^2.0.1
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  quantupi: ^0.0.5
  rxdart: ^0.27.7
  share_plus: ^7.0.2
  unity_ads_plugin: ^0.3.8
  url_launcher: ^6.1.11
  webview_flutter: ^3.0.4
  change_app_package_name: ^1.1.0
  facebook_app_events: ^0.19.0
  upgrader: ^7.1.0
  flutter_svg: ^1.1.6
  objectbox: ^2.1.0
  objectbox_flutter_libs: ^2.1.0
  scratcher: ^2.3.0
  hive_flutter: ^1.1.0










dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/Graphics/
    - assets/Sounds/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700