import 'package:flutter/material.dart';
export 'videoplayerscreen.dart';
export 'Profilepage.dart';
export 'Tweetspage.dart';
export 'Shortspage.dart';

// var finalamm = sendamount?.get(1);
// Box? account = Hive.box('account');
// Box? alertdata = Hive.box('alertdata');
// Box? alertdata2 = Hive.box('alertdata2');
// Box? transhistory = Hive.box('transhistory');
// Box? sendamount = Hive.box('sendamount');
// Box? assets = Hive.box('assets');
// Box? RealDemo = Hive.box('RealDemo');
// Box? trade = Hive.box('trade');
// Box? History = Hive.box('History');
// Box? TradeHistory = Hive.box('TradeHistory');
// Box? transwithdralhistory = Hive.box('transwithdralhistory');
// Box? userdata = Hive.box('userdata');
// Box? timework = Hive.box('timework');
// Color c6 = Color(0xff023047);
Color c6 = Color(0xff000000);
Color c3 = Colors.white;
Color c1 = Color(0xff000000);
Color c11 = Color(0xff03045e);
Color ct = Color(0xff83c5be);
Color ci = Color(0xffffd60a);
Color cb = Color(0xff000000);
Color blue = Color.fromARGB(255, 8, 209, 239);
Color buttoncolor = Color.fromARGB(255, 83, 76, 187);
Color green = Colors.green;
TextStyle textstyle = TextStyle(color: c3, fontWeight: FontWeight.bold);
