name: chatai
description: Nextonebox ai.
publish_to: 'none'
version: 2.0.0+2
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  awesome_notifications: ^0.7.4+1
  getwidget: ^3.0.1
  font_awesome_flutter: ^10.2.1
  http: ^0.13.5
  path_provider: ^2.0.11
  hive: ^2.2.3
  url_launcher: ^6.0.3
  clipboard: ^0.1.3
  flash: ^3.0.1
  share_plus: ^6.1.0
  double_back_to_close: ^2.0.0
  google_sign_in: ^6.1.0
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_core_platform_interface: ^4.5.2
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.1.4
  cloud_firestore: ^4.2.0
  webview_flutter: ^3.0.4
  google_mobile_ads: ^2.3.0
  rxdart: ^0.27.5
  audioplayers: ^4.0.1
  speech_to_text: ^6.1.1
  just_audio_background: ^0.0.1-beta.9
  flutter_tts: ^3.6.3
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0
  awesome_dialog: ^2.2.1
  quantupi: ^0.0.5
  change_app_package_name: ^1.1.0
  line_icons: ^2.0.1
  google_nav_bar: ^5.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
