name: onesite
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_nav_bar: ^5.0.6
  hive: ^2.2.3
  http: ^0.13.6
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  google_sign_in: ^6.1.3
  webview_flutter: ^3.0.4
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.8.0
  line_icons: ^2.0.1
  getwidget: ^3.1.1
  url_launcher: ^6.1.11
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.5
  sizer: ^2.0.15
  connectivity_plus: ^2.3.7
  carousel_slider: ^4.0.0
  animated_text_kit: ^4.2.1
  scrollable_positioned_list: ^0.3.5
  universal_html: ^2.0.4





flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

    - assets/potfolio/imgs/
    - assets/potfolio/icons/
    - assets/potfolio/gif/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/potfolio/fonts/montserrat/montserrat.ttf

    - family: Poppins
      fonts:
        - asset: assets/potfolio/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/potfolio/fonts/poppins/Poppins-Light.ttf
        - asset: assets/potfolio/fonts/poppins/Poppins-Bold.ttf
          weight: 900
        - asset: assets/potfolio/fonts/poppins/Poppins-Medium.ttf
          weight: 300
        - asset: assets/potfolio/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/potfolio/fonts/poppins/Poppins-Italic.ttf
          style: italic
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300